# -*- coding: utf-8 -*-
"""movies.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AjLS5e6Dmy1kFroUYS0dSC5GkbiGyJpY
"""

import pandas as pd

uri = "https://raw.githubusercontent.com/levibergamascki/pandas/main/movies.csv"
filmes = pd.read_csv(uri)

filmes.columns = [ "filmeId", "titulo", "generos" ]
filmes
# filmes.head - devolve os cinco primeiros registros

uri = "https://raw.githubusercontent.com/levibergamascki/pandas/main/ratings.csv"
notas = pd.read_csv(uri)

notas.columns = ["usuarioId", "filmeId", "nota", "momento"]

notas.head() # series

notas["nota"].unique()

notas["nota"].mean()

notas["nota"].min()

notas["nota"].max()

notas.describe()

notas.nota.plot(kind='hist')

