# -*- coding: utf-8 -*-
"""movies.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AjLS5e6Dmy1kFroUYS0dSC5GkbiGyJpY
"""

import pandas as pd

uri = "https://raw.githubusercontent.com/levibergamascki/pandas/main/movies.csv"
filmes = pd.read_csv(uri)

filmes

